# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for pip
  - package-ecosystem: 'pip'
    # Look for `pyproject.toml` and `lock` files in the `root` directory
    directory: '/'
    # Check the pip registry for updates every day (weekdays)
    schedule:
      interval: 'daily'
    reviewers:
      - 'm-sanchez-dev'
